# Created using wingetcreate 0.3.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: TheNuProjectContributors.nu
PackageVersion: 0.34.0
PackageLocale: en-US
Publisher: The Nu Project Contributors
PackageName: nu
PackageUrl: https://github.com/nushell/nushell
License: MIT
LicenseUrl: https://github.com/nushell/nushell/blob/main/LICENSE
ShortDescription: A new type of shell
Moniker: nushell
Tags:
- shell
ManifestType: defaultLocale
ManifestVersion: 1.0.0

